"""empty message

Revision ID: 85caa018b54f
Revises: 
Create Date: 2021-02-04 06:45:20.434752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85caa018b54f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'category',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('category', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('category', 'questions', 'categories', ['category'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('questions', 'category',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
